#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: index.html.twig


guide:
  path: /guide
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: guide.html.twig

adminindex:
  path: /admin
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: admin_index.html.twig    


#admin_article_index:
#  path: /admin/article/
#  controller: App\Controller\Admin\ArticleController::index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
